### ISSUE TITLE
BCL delivery process

### ISSUE THREAD

**Issue by lokeshbio** [ctg-lund/Yggdrasil#14]

**Comment by chaetognatha** [comment]
The samplesheet for rawdata deliveries will be called the same as every other, but it will only contain project ID on one line, no commas or anything else, so a file with one line that is the project ID! (there should also be flags to specify both project ID and rawdata delivery, in which case we shouldnt need a samplesheet at all!)

**Comment by chaetognatha** [comment]
Perhaps it will be useful to have this line that I use to do md5sum over multiple processes on LSENS:

```bash 
module load parallel/20220722
raw=$1
parallel -j8 "md5sum {} >> ${raw}/md5.txt" ::: $(find ${raw}/Data -type f -print)
```

**Comment by lokeshbio** [comment]
We should probably include what kind of delivery each project requires in the sample_sheet! At the moment, the example samplesheet look like this:

```
[Yggdrasil_Projects],,,
Project_ID,bcl,fastq,fastq_screen,fastq_screen_ref
2022_000,0,1,0,NA
```

If we keep adding more pipelines, it is not sustainable to keep adding columns! i would rather have these end deliveries set as Keys like BCL, FASTQ, FASTQ_SCREEN, RNASEQ, METHYLSEQ and so on..  that they are just in one column! then we can have these as binary parameters in Yggdrasil! 

```
#In samplesheet

[Yggdrasil_Projects],,,
Project_ID,bcl,fastq,fastq_screen,fastq_screen_ref
2022_000,FASTQ
2022_001, RNASEQ

# Then in Yggdrasil nextflow script: we can set these parameters as

params.rnaseq = TRUE #specifically for 2022_001
```

**Comment by lokeshbio** [comment]
BCL delivery process needs to be discussed
