### ISSUE TITLE
Delivery process

### ISSUE THREAD

**Issue by chaetognatha** [ctg-lund/Yggdrasil#5]
The delivery is a simple rsync of the complete processed data to LFS

**Comment by lokeshbio** [comment]
The process is now written to have the folder structure we wanted like: `${proj}/${fc}/0_fastq/` and `${proj}/${fc}/1_qc/`. Here the publishdir has the default location of where the seq-only files need to be deposited and in case of test runs it can also be given as `--outdir` in NF

**Comment by chaetognatha** [comment]
Working on pull request!
