### ISSUE TITLE
Test and put a sequencing only pipeline in production

### ISSUE THREAD

**Issue by chaetognatha** [ctg-lund/Yggdrasil#6]
- [x] Stable demux process
- [x] QC process
- [x] Delivery process

* We need to develop with the fact in mind that we will need to be able to switch in another workflow before the delivery process, I am not 100% clear on what the best strategy to do this is

**Comment by lokeshbio** [comment]
The only part left is now to test a flowcell with multiple projects and eventually also test same project in multiple flowcells

**Comment by chaetognatha** [comment]
with the new members of bnf we moved into a modular python launcher to do this, it is working well enouch right now
